### ISSUE TITLE
Basic Setup Instructions - Migrate from MR Wiki to Git Wiki

### ISSUE THREAD

**Issue by malcolmwhat** [mcgill-robotics/compsys#15]
In the section `Installation - Prerequisites` of the README it currently refers the user to follow the basic setup instructions on the McGill Robotics Wiki. 

We are no longer using the McGill Robotics Wiki for software purposes. We should migrate that wiki page into a git wiki page for this repository. 

This should include: 

- Link to a good VM setup guide (I suggest [this article](http://linus.nci.nih.gov/bdge/installUbuntu.html))
- Installation of git via `apt-get`
- Generation of ssh keys, adding the public key to Git

**Comment by malcolmwhat** [comment]
@anassinator Missing anything?

**Comment by anassinator** [comment]
I don't think we should have a wiki just for that. We could clarify it in the README for now.

I think we can clarify how to install git and link to the GitHub SSH key setup tutorial. As for VMs, I don't think we should link to something like that, because the instructions should work for all platforms. I would suggest just stating Ubuntu 14.04 as a requirement, whether on a VM or barebones, and removing the existing link.

We could state that VMWARE is free for McGill students however.

**Comment by malcolmwhat** [comment]
Good point about the VM. Ubuntu is already stated as a requirement in basic setup, I'll add 

> whether on a VM or barebones. 

though.
